### PR TITLE
Implement initial messaging logic and restructure routes/controllers.

### PR DESCRIPTION
**Pull request by jaheemprevost**
The following Pull request includes:

Updates to code base written in the branch "main" (pending review)
Creation of Message model
Creation of Conversation model 
Creation of User controller
Creation of Message controller
Creation of (new) user-routes
Updates to auth-user-controller: renamed to just auth-controller
Updates to (original) user-routes: renamed to auth-routes
Updates to app.ts Include: modification of existing route middleware  
Creation of global.d.ts (in-progress)

Encountered Issues: 

While trying to access the userId property on the req.user object, I encountered an error that told me that the proper userId just didn't exist on type User, even though req.user should contain the decoded payload of the assigned JWT token which would contain the userId, userName, and email properties. I did some research to find a solution to this and incorporated a global.d.ts file although this did not solve the issue, I also created a tsconfig.file and that seemed have resolved the error but upon running the dev script I encountered the error again inside of the console this time. I removed it for the time being and commented out all instances inside the controllers where the userId might have been accessed to avoid unwanted errors until a proper solution can be found.

```
return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
src/controllers/message-controller.ts:93:13 - error TS2339: Property 'userId' does not exist on type 'User'
```
This update is in reference to the following Jiras:
https://bbpracticum.atlassian.net/browse/CP2-10
https://bbpracticum.atlassian.net/browse/CP2-21

### CODE REVIEW

**Comment by royemosby** [comment]
Big PR- I won't be able to look at it until Saturday AM

**Comment by jaheemprevost** [comment]
Update:
Created getUsers and getUser functions in user-controller
Updated createMessage function to query a conversation regardless of the order of the user ids
Implemented work around for the User type issue thanks to Abdul
Modified passport-config to populate req.user with only the necessary properties

**Comment by jaheemprevost** [comment]
Updates:
Updated user-model to include a field that stores object ids that reference conversations 
Updated getUsers function to filter between users who have conversed with the currently logged in users and those that have not
Updated getUserConversations function to also include the createdAt field for conversion on frontend
Updated createMessage function to ensure that a user is unable to send a message to themself
Updated auth-controller and auth-router to account-controller and account-router and modified existing routes to match

**Review by mdmontes — APPROVED** [review]
All updates worked succesfully, 

Link to test results: https://bbpracticum.atlassian.net/wiki/spaces/BP/pages/6750224/6+3+2023+Meeting+at+11+00+am

**Comment by mdmontes** [comment]
Link to test results from my review: https://bbpracticum.atlassian.net/wiki/spaces/BP/pages/6750224/6+3+2023+Meeting+at+11+00+am

**Review by royemosby — APPROVED** [review]
GTG

**Pull request merged**
