### PR TITLE
Profile

### PR DESCRIPTION
**Pull request by Abdulaiman**
This is a continuation from the socket.io_implement branch, I was able to 

1) configure cloudinary, a cloud-base image storage platform to store Images on the cloud and provide access to them using a url

2) added an npm package called multiparty to parse the form data (image file and text inputs)

combining the two i was able to upload images to the cloud and retreive them with ease

the front end team should make a Patch request to this Api ("http://localhost:8000/api/v1/users/:userId/update-user") sending the data to be updated, an image or text or both, using form-data not on the body object.

if a user have no profile picture, and is uploading for the first time only the image should be sent down, however if the user already have a profile picture and wants to update it, the public_id of the previous image should be sent together with the new image so the older image can be removed from the cloudinary assets.

if a user wishes to change their name and also there profile picture simultaneously, both the userName field and the image file should be sent through the form-data and both will be updated, if a user choose to change just one at a time it should be sent down only that would be updated...

I will be sharing the .env keys to everyone through the group slack channel

### CODE REVIEW

**Comment by royemosby** [comment]
@Abdulaiman please pull in main then I can review

**Review by frankstepanski — APPROVED** [review]
Approved to be updated..

**Review by royemosby — COMMENTED** [review]
👍

**Review by royemosby — APPROVED** [review]
👍

**Review by mdmontes — CHANGES_REQUESTED** [review]
Test results included here: 
https://bbpracticum.atlassian.net/wiki/spaces/BP/pages/7667715/Post-Man+Test+Results+User+Upload+of+images
 
1. Pull request has a lot of code from the "implement_socket.IO" branch, which has been merged into "main". I wanted to recommend we pull Main into this branch to resolve any conflicts, with all code not related to Uploading profile pics that is coming from main being pulled into this "Profile" branch, prior to re-merging into main.
2.  As outlined in the test results, the code could benefit from error-handling that informs users they have tried to load a wrong file type (like say, trying to load a text file rather than image file)

**Review by mdmontes — APPROVED** [review]
Updates requested have been implemented!

**Pull request merged**
